import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import React, {useState} from 'react';

//a single component for my single component front end.
//displays a greeting and have a button that changes the other text on the screen.
export default function Home() {
  const [response, setResponse] = useState("Radio Silence")
  
  const callApi = () => {
    axios.get('http://localhost:3001/button')
    .then(res => {
        setResponse(res.data.response);
    })
    .catch(function (error) {
        console.log(error);
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Jack's App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Jack's App
        </h1>
        <h4>
          {response}
        </h4>
        <button onClick={callApi}>Call API</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
